### ISSUE TITLE
MAC address no longer appears when registering a kit

### ISSUE THREAD

**Issue by peters-rebecca** [fablabbcn/smartcitizen-kit-2x#75]
The MAC address no longer appears when registering a kit in terminal, this could be linked to the changes that were made where the MAC address can be found with the `netinfo` command instead of `config`.

**Comment by oscgonfer** [comment]
Hi @peters-rebecca solved in https://github.com/fablabbcn/smartcitizen-kit-2x/commit/b23b27d4821a44c385579469df78c9f2b6ac4e78
